### ISSUE TITLE
Hi hakob

### ISSUE THREAD

**Issue by pkdcryptos** [Hakob23/Trade#1]
Hi hakob,

Good work for trade project. Trx to tkoen is working w/o any issues. But token to try or token to token always fail with revert opcode. Any clue ? Great code by the way.

**Comment by pkdcryptos** [comment]
looks like you need to approve the justswap exchnage within the contract before tokentotokenswap
like:
require(ITRC20(fuel).approve(address(justswap), 1000000000000000000000), 'approve failed!');

pls suggest

**Comment by Hakob23** [comment]
Hi @pkdcryptos. Thanks for the interest. The code that you see on GitHub is not final. But yes, the final version should include modifications with approval requests to the trading contract before you call any function from JustSwap Exchange. Otherwise, it should work fine.
Also, could you please tell me how did you find the code and on which project do you want to implement it?
